# Generated by Django 3.1 on 2020-08-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200818_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='headline',
            new_name='topic',
        ),
    ]
